# .github/workflows/test.yml
name: test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Python (3.10 is supported on ubuntu-latest)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4) Run your tests
      - name: Run test
        run: |
          cd code
          bash test.sh
